apiVersion: v1
appVersion: 8.6-community
name: sonarqube
description: SonarQube is an open sourced code quality scanning tool
version: 9.2.6-bb.2
keywords:
  - coverage
  - security
  - code
  - quality
home: https://www.sonarqube.org/
icon: https://www.sonarqube.org/assets/logo-31ad3115b1b4b120f3d1efd63e6b13ac9f1f89437f0cf6881cc4d8b5603a52b4.svg
sources:
  - https://github.com/SonarSource/docker-sonarqube
maintainers:
  - name: rjkernick
    email: rjkernick@gmail.com
  - name: tsiddique
    email: tsiddique@live.com
