dependencies:
- name: postgresql
  version: 8.6.4
  repository: file://./deps/postgresql
  condition: postgresql.enabled
- name: gluon
  version: "0.2.10"
  repository: "oci://registry.dso.mil/platform-one/big-bang/apps/library-charts/gluon"
